// DOM integration only. No dev server, browser, WebGL frame or visual QA is implied.
import fs from 'node:fs';
import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {Window}=await import(process.env.CLASSROOM_HAPPY_DOM_MODULE||'happy-dom');
const root=fileURLToPath(new URL('../dist/',import.meta.url)).replace(/\/$/,'');
const win=new Window({url:'http://classroom.test',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true,enableJavaScriptEvaluation:false}});
win.document.write(fs.readFileSync(root+'/index.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));
for(const k of ['window','document','localStorage','history','navigator','HTMLElement','CustomEvent','Event','File','Blob'])Object.defineProperty(globalThis,k,{value:k==='window'?win:win[k],configurable:true});
win.lucide={createIcons(){}};
const dialog=win.document.querySelector('dialog');dialog.showModal=function(){this.setAttribute('open','');};dialog.close=function(){this.removeAttribute('open');};
Object.defineProperty(win.document,'modelContext',{value:{registerTool(){}},configurable:true});
const originalInterval=globalThis.setInterval;globalThis.setInterval=()=>1;
const stub=`class ClassroomScene {constructor(canvas,options){this.options=options;this.renderer={};this.zoom=1;this.keys={};this.joy={};options.onReady();}sync(){}speak(){}zoomBy(){}resetView(){}rotate(){}resumeGuide(){}}`;
const source=fs.readFileSync(root+'/app.js','utf8').replace("import {ClassroomScene} from './scene.js';",stub).replace(/from '\.\/([^']+)\.js'/g,(_,file)=>`from '${pathToFileURL(root+'/'+file+'.js').href}'`);
const errors=[];const previousError=console.error;console.error=(...args)=>{errors.push(args.map(String).join(' '));previousError(...args);};
await import('data:text/javascript;base64,'+Buffer.from(source+'\nglobalThis.communityUI={getState:()=>state,commit,open:(page,id)=>beta.show(page,id),staffList,staffConsult,messenger,toast};').toString('base64'));
const $=s=>win.document.querySelector(s),$$=s=>[...win.document.querySelectorAll(s)],hydrated=new WeakSet();
function hydrate(){for(const sel of $$('select'))if(!hydrated.has(sel)){hydrated.add(sel);const def=sel.querySelector('option[selected]');if(def)sel.value=def.value;}}
async function click(action,extra=''){const el=action==='close'?$('#modal-close'):$(`[data-action="${action}"]${extra}`);assert.ok(el,'Missing '+action+extra);assert.equal(el.disabled,false,'Disabled '+action);el.click();await new Promise(r=>setImmediate(r));hydrate();assert.deepEqual(errors,[]);}
const api=globalThis.communityUI,read=()=>JSON.parse(win.localStorage.getItem('classroom-days-alpha-v1'));
const note='학생과 직접 확인한 자료와 다음 활동의 방법을 구체적으로 기록했습니다.';
hydrate();assert.equal($('#modal').classList.contains('setup-modal'),true);assert.equal($('.setup-advanced').open,false);assert.equal($$('.portrait-choice').length,8);$('#setup-region').value='newtown';$('#setup-grade').value='5';$('#setup-count').value='8';await click('start-game');assert.equal(read().tutorial.step,0);assert.equal(read().tutorial.status,'active');const initialDate=[api.getState().day,api.getState().minute];assert.equal($('[data-action="tutorial-prev"]').disabled,true);await click('tutorial-next');assert.equal(read().tutorial.step,1);await click('tutorial-prev');assert.equal(read().tutorial.step,0);await click('tutorial-skip');assert.equal(read().tutorial.status,'skipped');assert.equal(api.getState().academic.acknowledged,false);assert.deepEqual([api.getState().day,api.getState().minute],initialDate);$('#modal-body').scrollTop=640;await click('beta-ack');assert.equal($('#modal-body').scrollTop,640);assert.equal($('[data-action="class-curriculum"]').disabled,false);await click('close');await click('settings');await click('tutorial-replay');for(let i=0;i<7;i++)await click('tutorial-next');assert.equal(read().tutorial.status,'completed');assert.deepEqual([api.getState().day,api.getState().minute],initialDate);await click('close');await click('primary');assert.equal($('#modal-body').scrollTop,0);await click('beta-begin');console.log('PASS: compact setup, tutorial start/back/skip/replay/finish without time changes, school acknowledgement scroll retained, new navigation reset.');
const s=api.getState();function at(day=1,minute=520){s.day=day;s.minute=minute;s.room=s.classLocation='classroom';s.journey=null;s.groupActivity=null;s.teacherPlanner.entries=[];api.commit();}
at();api.open('community');hydrate();assert.match($('#modal-title').textContent,/사람과 일상/);await click('beta-belongings');assert.equal($$('.beta-item-grid article').length,8);$('#cx-inspect-consent').checked=true;await click('beta-inspect','[data-scope="desk"]');assert.equal(read().community.checks[0].consent,true);
const item=s.community.belongings[s.students[0].personKey][0];$('#cx-place-'+item.id).value='lost';await click('beta-item-move',`[data-id="${item.id}"]`);$('#cx-lost-owner-'+item.id).value='s0';$('#cx-clue-'+item.id).value='필통의 이름표와 색을 같이 확인';await click('beta-lost-return');assert.equal(read().community.belongings[s.students[0].personKey][0].place,'bag');await click('beta-aid-lend');const aid=s.community.loans[0];await click('beta-aid-return',`[data-id="${aid.id}"]`);assert.equal(read().community.loans[0].returned,true);
await click('beta-family');$('#cx-parent-name').value='이새봄 보호자';await click('beta-family-add');const parent=Object.values(s.community.guardians).find(g=>g.name==='이새봄 보호자');assert.ok(parent);for(const e of $$(`[data-guardian="${parent.key}"]`))e.checked=true;await click('beta-family-permissions',`[data-id="${parent.key}"]`);$('#cx-message-'+parent.key).value=note;await click('beta-family-message',`[data-id="${parent.key}"]`);assert.ok($$('blockquote').some(x=>x.textContent.includes('구분해서')));$('#cx-consent-'+parent.key).value='교내 독서 발표';await click('beta-consent',`[data-id="${parent.key}"][data-agree="no"]`);assert.equal(read().community.consents[0].agree,false);
at(1,900);api.open('family');hydrate();$('#cx-arrival-name').value='유은결';$('#cx-arrival-gender').value='남';await click('beta-transfer-in');const incoming=s.students.at(-1);assert.equal(s.students.length,9);assert.equal($('#cx-student').value,incoming.id);$('#cx-out-school').value='바다빛초등학교';$('#cx-out-note').value=note;await click('beta-transfer-confirm');assert.match($('#modal-title').textContent,/전출 인계 확인/);await click('beta-transfer-out');assert.equal(read().students.length,8);assert.ok(read().community.transfers.some(t=>t.kind==='out'&&t.student.id===incoming.id));
await click('beta-election-full');await click('beta-election-start');await click('beta-election-nominate');await click('beta-election-campaign','[data-id="poster"]');assert.equal($('[data-action="beta-election-campaign"][data-id="poster"]').disabled,true);await click('beta-election-campaign','[data-id="debate"]');await click('beta-election-vote');assert.ok(read().democracy.elections[0].result);assert.match($('#modal-title').textContent,/전교 임원 선거/);
await click('beta-governance');$('#cx-committee-stand').checked=true;await click('beta-committee-election');assert.equal(read().democracy.committee.length,1);$('#cx-vol-day').value='5';await click('beta-volunteer-add');assert.equal(read().democracy.volunteers.length,1);await click('beta-volunteer-replace');assert.equal(read().democracy.volunteers[0].replacement,'학교 지원 인력 요청');
at(2,900);s.students.forEach(st=>st.after='늘봄');api.open('evaluation');hydrate();$('#cx-assess-subject').value='국어';$('#cx-assess-goal').value=note;await click('beta-assessment-run');for(const st of s.students)$('#cx-evidence-'+st.id).value=note;await click('beta-assessment-save');await click('beta-assessment-final');assert.equal(read().schoolReview.assessments[0].status,'final');assert.equal($('[data-action="beta-assessment-save"]').disabled,true);
await click('beta-operations-detail');$('#cx-prep-detail').value=note;await click('beta-preparation');assert.equal(read().schoolReview.preparation.length,1);$('#cx-workshop-text').value=note;await click('beta-book-workshop');assert.equal(read().schoolReview.workshops.length,1);$('#cx-closure-day').value='7';$('#cx-closure-reason').value='학교 시설 점검에 따른 임시 휴업 결정';await click('beta-school-closure');assert.equal(read().academic.calendar.find(d=>d.day===7).school,false);await click('beta-closure-undo');assert.equal(read().academic.calendar.find(d=>d.day===7).school,true);
api.open('library');hydrate();assert.equal($$('.book-scene').length,12);await click('beta-library','[data-id="umbrella"]');assert.equal($$('.book-scene').length,1);await click('beta-operations-detail');assert.match($('#modal-title').textContent,/학교 운영 세부/);
const {validateSave}=await import(pathToFileURL(root+'/model.js').href);assert.equal(validateSave(read()),true);assert.deepEqual(errors,[]);
console.log('PASS: community, consent, inventory, lost property, aids, private guardian replies, transfers, elections, committee, volunteer cover, assessment, work preparation, illustrated books, closure and save DOM flows. WebGL renderer stubbed; no visual claims.');
at(3,520);api.open('belongings');hydrate();$('#cx-aid').value='독서대';await click('beta-aid-lend');const damaged=s.community.loans.at(-1);$('#cx-aid-condition-'+damaged.id).value='점검 필요';await click('beta-aid-return',`[data-id="${damaged.id}"]`);assert.equal([...$('#cx-aid').options].some(o=>o.value==='독서대'),false);$('#cx-aid-note-'+damaged.id).value='받침이 흔들려 사용을 멈추고 종이 자료로 대체';const budgetBeforeRepair=s.budget;await click('beta-aid-repair',`[data-id="${damaged.id}"]`);assert.equal(read().community.loans.at(-1).repair.status,'requested');assert.ok(s.teacherPlanner.entries.some(e=>e.aidLoanId===damaged.id));at(damaged.repair.due,520);api.open('belongings');hydrate();await click('beta-aid-receive',`[data-id="${damaged.id}"]`);assert.equal(read().community.loans.at(-1).repair.status,'closed');assert.ok([...$('#cx-aid').options].some(o=>o.value==='독서대'));$('#cx-aid').value='독서대';await click('beta-aid-lend');assert.equal(s.budget,budgetBeforeRepair);assert.equal(validateSave(read()),true);console.log('PASS: actual DOM damaged return → admin request → scheduled notice → receipt → reloan, without classroom budget charge.');
// Choice-first forms and the actual new staff workflow, using the same DOM handlers as players.
at(10,520);api.staffList();hydrate();assert.equal($$('.staff-task').length,16);await click('staff-chat','[data-id="aftercare"]');
const choose=(id,value)=>{const select=$('#'+id);assert.ok(select);select.value=value;select.dispatchEvent(new win.Event('change',{bubbles:true}));};
assert.equal($('#message-text').hidden,true);assert.equal([...$('#message-text-choices').options].at(-1).value,'other');
choose('message-text-choices','other');assert.equal($('#message-text').hidden,false);$('#message-text').value='오늘 오후 학생의 물통 인계 방법을 알려 주세요.';$('#message-text').dispatchEvent(new win.Event('input',{bubbles:true}));choose('message-text-choices','0');assert.equal($('#message-text').hidden,true);assert.ok($('#message-text').value.includes('확인'));choose('message-text-choices','other');assert.match($('#message-text').value,/물통/);$('#message-form').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setImmediate(r));hydrate();assert.equal(read().staffNetwork.queue.at(-1).status,'waiting');const pendingCount=s.messages.length;api.commit();assert.equal(s.messages.length,pendingCount);
await click('chat-suggestion');const sent=$$('[data-action="chat-suggestion"]').find(b=>b.disabled);assert.ok(sent);assert.equal(sent.getAttribute('aria-disabled'),'true');
s.minute=780;api.commit();api.messenger('staff');hydrate();assert.equal(s.staffNetwork.queue.every(q=>q.status==='answered'),true);assert.ok($$('.message').some(m=>m.textContent.includes('배소연')));
await click('staff-consult');const requestedSlot=$('#staff-slot').value;await click('staff-request');const consultation=s.staffNetwork.consultations.at(-1);assert.equal(consultation.status,'requested');assert.equal($('#toast').parentElement,$('#modal'));assert.ok($('#toast').classList.contains('show'));
s.minute+=2;api.commit();api.staffConsult('aftercare',consultation.id);hydrate();assert.equal(consultation.status,'scheduled');s.day=consultation.day;s.minute=consultation.start-10;api.commit();await click('go-room','[data-id="art"]');api.staffConsult('aftercare',consultation.id);hydrate();choose('staff-note-'+consultation.id+'-choices','0');await click('staff-attend',`[data-id="${consultation.id}"]`);assert.equal(read().staffNetwork.consultations.at(-1).status,'completed');assert.ok(s.notes.teacher.some(n=>n.text.includes('배소연')));
api.open('governance');hydrate();const cover=s.staffNetwork.covers.find(c=>c.status==='reported');assert.ok(cover);await click('beta-cover-ack',`[data-id="${cover.id}"]`);assert.equal(read().staffNetwork.covers.find(c=>c.id===cover.id).status,'confirmed');assert.equal(validateSave(read()),true);
console.log('PASS: choices → Other with draft preservation → queued staff messages and disabled replies → request/reply/scheduler → room visit/attendance → school cover receipt. Toast is in the dialog top layer.');

// beta.7: actual handlers for repeated selection, worksheet, care, work and leave.
at(10,520);await click('close');await click('settings');await click('practice-start');assert.equal($('#practice-guide').hidden,false);await click('practice-toggle');assert.equal(read().tutorial.practice.collapsed,true);await click('practice-skip');assert.equal($('#practice-guide').hidden,true);
await click('primary');$('#modal-body').scrollTop=355;await click('morning-select','[data-id="drawing"]');assert.equal($('#modal-body').scrollTop,355);await click('morning-select','[data-id="puzzle"]');assert.equal($('#modal-body').scrollTop,355);await click('close');
const {todaySchedule,takeAttendance}=await import('../dist/model.js');const lesson=todaySchedule(s).find(l=>!l.specialist&&!l.event);s.minute=lesson.start;takeAttendance(s,{s0:'질병결석'});api.commit();await click('primary');await click('worksheet-open');assert.match($('#modal-title').textContent,new RegExp(s.config.grade+'학년'));await click('worksheet-issue');assert.equal(read().lessonWorksheets.at(-1).participantIds.includes('s0'),false);$('#modal-body').scrollTop=270;await click('worksheet-answer');assert.equal($('#modal-body').scrollTop,270);assert.ok($$('[data-action="worksheet-answer"]').every(b=>b.disabled));await click('primary');await click('lesson-mode');await click('lesson-finish');assert.equal(read().lessonResults.at(-1).contentId,read().lessonWorksheets.at(-1).cardId);
at(10,900);await click('close');await click('primary');await click('care-open');$('#modal-body').scrollTop=280;await click('care-effort','[data-id="together"]');assert.equal($('#modal-body').scrollTop,280);if(s.classroomCare.items.length)await click('care-clean','[data-id="20"]');assert.equal(read().classroomCare.items.length,0);
await click('close');at(10,900);await click('primary');await click('duty-perform','[data-id="documents"]');assert.equal(s.minute,920);assert.equal(read().teacherDuty.work.at(-1).kind,'documents');await click('duty-open');
$('#duty-type').value='sickEarly';$('#duty-type').dispatchEvent(new win.Event('change',{bubbles:true}));hydrate();$('#duty-start').value='930';$('#duty-start').dispatchEvent(new win.Event('change',{bubbles:true}));hydrate();$('#modal-body').scrollTop=460;await click('duty-request');assert.equal($('#modal-body').scrollTop,460);const leave=s.teacherDuty.requests.at(-1);$('#handoff-'+leave.id).checked=true;await click('duty-approve','[data-id="'+leave.id+'"]');assert.equal(read().teacherDuty.requests.at(-1).status,'approved');await click('duty-depart','[data-id="'+leave.id+'"]');assert.equal(s.minute,1000);assert.equal(read().teacherDuty.requests.at(-1).minutes,70);assert.equal(read().teacherDuty.requests.at(-1).status,'used');assert.equal(validateSave(read()),true);await click('next-day');assert.equal(s.teacherDuty.away,null);
console.log('PASS: interactive tutorial, repeat-choice/worksheet/leave scroll preservation, grade worksheet → lesson, cleaning, timed work and approved sick early leave via actual DOM.');

at(258,1000);s.ended=true;s.academic.phase='closed';api.commit();assert.equal(s.ended,false);await click('close');await click('primary');await click('next-day');assert.equal(s.day,259);at(259,1000);await click('primary');await click('week-summary');assert.match($('#modal-title').textContent,/다음 학년도/);assert.ok($('#bc-grade').getBoundingClientRect);await click('beta-career-propose');await click('beta-career-accept');await click('beta-career-next');assert.equal(s.academic.year,2031);assert.equal(s.academic.phase,'preparation');assert.equal(s.career.archives.length,1);assert.equal(validateSave(read()),true);console.log('PASS: February 27 recovery, February 28 close, assignment acceptance and next-year curriculum through actual DOM buttons.');
// beta.8: real application save preview/restore and emoji input, then the real speech DOM renderer.
await click('close');await click('settings');await click('vault-open');
await click('vault-manual','[data-id="0"]');$('#vault-label').value='새 학년도 준비 📚';await click('vault-manual-confirm');
const {VAULT_KEY,createSaveVault}=await import('../dist/save-vault.js'),vault=createSaveVault(win.localStorage),snapshot=vault.candidate('manual:0').state;
api.getState().budget-=100;api.getState().notes.teacher.push({date:'3월 4일 09:00',text:'미리보기 뒤의 별도 기록'});api.commit();
await click('vault-preview','[data-id="manual:0"]');assert.equal(api.getState().budget,snapshot.budget-100);assert.match($('#modal-title').textContent,/미리보기/);
await click('vault-restore');assert.equal(api.getState().budget,snapshot.budget);assert.deepEqual(api.getState().notes.teacher,snapshot.notes.teacher);
const broken=JSON.parse(win.localStorage.getItem(VAULT_KEY));broken.auto[0].digest='00000000';const brokenRaw=JSON.stringify(broken);win.localStorage.setItem(VAULT_KEY,brokenRaw);api.commit();assert.equal($('#storage-warning').hidden,false);
await click('settings');await click('vault-open');await click('vault-preview','[data-id="auto:1"]');assert.equal(win.localStorage.getItem(VAULT_KEY),brokenRaw);await click('vault-restore');assert.equal(vault.boot().status,'ready');assert.equal(vault.read().bank.quarantine.vault,brokenRaw);
api.messenger('staff');hydrate();choose('message-text-choices','other');$('#message-text').value='독서 협의 부탁드립니다.';$('#message-text').setSelectionRange($('#message-text').value.length,$('#message-text').value.length);await click('emoji-insert','[data-emoji="📚"]');assert.ok($('#message-text').value.endsWith('📚'));$('#message-form').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setImmediate(r));hydrate();assert.ok($$('.message p').some(p=>p.textContent.includes('📚')));assert.ok($$('.message .text-date').length>0);assert.ok($$('.message .text-person').length>0);assert.ok($$('.message .text-time').length>0);
const actual=api.getState(),sceneSource=fs.readFileSync(root+'/scene.js','utf8').replace("from 'three'","from '"+pathToFileURL(root+'/assets/three.module.js').href+"'").replace(/from '\.\/([^']+)'/g,(_,file)=>"from '"+pathToFileURL(root+'/'+file).href+"'");
const {ClassroomScene:RealScene}=await import('data:text/javascript;base64,'+Buffer.from(sceneSource).toString('base64'));
const pupil=actual.students[0],speech={actors:new Map([[pupil.id,{group:{visible:true}}]]),bubbles:[],getState:()=>actual};
RealScene.prototype.speak.call(speech,pupil.id,'3월 5일 09:00에 '+actual.students[1].name+'와 책을 읽고 싶어요.',pupil.name);
assert.ok($('.bubble .bubble-copy').textContent.endsWith('📚'));assert.equal($('.bubble .text-date').tagName,'STRONG');assert.equal($('.bubble .text-time').tagName,'STRONG');assert.ok($('.bubble .text-person'));assert.equal(win.document.title,'오늘 우리 교실은 · 정식 베타');
console.log('PASS: manual save preview/restore, corrupt-head recovery with original preservation, emoji composer and real student bubble formatting.');
globalThis.setInterval=originalInterval;console.error=previousError;await win.happyDOM.abort();process.exit(0);
