// DOM integration only. No dev server, browser, WebGL frame or visual QA is implied.
import fs from 'node:fs';
import {fileURLToPath,pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {Window}=await import(process.env.CLASSROOM_HAPPY_DOM_MODULE||'happy-dom');
const root=fileURLToPath(new URL('../dist/',import.meta.url)).replace(/\/$/,'');
const win=new Window({url:'http://classroom.test',settings:{disableJavaScriptFileLoading:true,disableCSSFileLoading:true,enableJavaScriptEvaluation:false}});
win.document.write(fs.readFileSync(root+'/index.html','utf8').replace(/<script[\s\S]*?<\/script>/g,''));
for(const k of ['window','document','localStorage','history','navigator','HTMLElement','CustomEvent','Event','File','Blob'])Object.defineProperty(globalThis,k,{value:k==='window'?win:win[k],configurable:true});
win.lucide={createIcons(){}};
const dialog=win.document.querySelector('dialog');dialog.showModal=function(){this.setAttribute('open','');};dialog.close=function(){this.removeAttribute('open');};
Object.defineProperty(win.document,'modelContext',{value:{registerTool(){}},configurable:true});
const originalInterval=globalThis.setInterval;globalThis.setInterval=()=>1;
const stub=`class ClassroomScene {constructor(canvas,options){this.options=options;this.renderer={};this.zoom=1;this.keys={};this.joy={};options.onReady();}sync(){}speak(){}zoomBy(){}resetView(){}rotate(){}resumeGuide(){}}`;
const source=fs.readFileSync(root+'/app.js','utf8').replace("import {ClassroomScene} from './scene.js';",stub).replace(/from '\.\/([^']+)\.js'/g,(_,file)=>`from '${pathToFileURL(root+'/'+file+'.js').href}'`);
const errors=[];const previousError=console.error;console.error=(...args)=>{errors.push(args.map(String).join(' '));previousError(...args);};
await import('data:text/javascript;base64,'+Buffer.from(source+'\nglobalThis.communityUI={getState:()=>state,commit,open:(page,id)=>beta.show(page,id),staffList,staffConsult,messenger,toast};').toString('base64'));
const $=s=>win.document.querySelector(s),$$=s=>[...win.document.querySelectorAll(s)],hydrated=new WeakSet();
function hydrate(){for(const sel of $$('select'))if(!hydrated.has(sel)){hydrated.add(sel);const def=sel.querySelector('option[selected]');if(def)sel.value=def.value;}}
async function click(action,extra=''){const el=action==='close'?$('#modal-close'):$(`[data-action="${action}"]${extra}`);assert.ok(el,'Missing '+action+extra);assert.equal(el.disabled,false,'Disabled '+action);el.click();await new Promise(r=>setImmediate(r));hydrate();assert.deepEqual(errors,[]);}
const api=globalThis.communityUI,read=()=>JSON.parse(win.localStorage.getItem('classroom-days-alpha-v1'));
const note='학생과 직접 확인한 자료와 다음 활동의 방법을 구체적으로 기록했습니다.';
hydrate();assert.equal($('#modal').classList.contains('setup-modal'),true);assert.equal($('.setup-advanced').open,false);assert.equal($$('.portrait-choice').length,8);$('#setup-region').value='newtown';$('#setup-grade').value='5';$('#setup-count').value='8';await click('start-game');assert.equal(read().tutorial.step,0);assert.equal(read().tutorial.status,'active');const initialDate=[api.getState().day,api.getState().minute];assert.equal($('[data-action="tutorial-prev"]').disabled,true);await click('tutorial-next');assert.equal(read().tutorial.step,1);await click('tutorial-prev');assert.equal(read().tutorial.step,0);await click('tutorial-skip');assert.equal(read().tutorial.status,'skipped');assert.equal(api.getState().academic.acknowledged,false);assert.deepEqual([api.getState().day,api.getState().minute],initialDate);$('#modal-body').scrollTop=640;await click('beta-ack');assert.equal($('#modal-body').scrollTop,640);assert.equal($('[data-action="class-curriculum"]').disabled,false);await click('close');await click('settings');await click('tutorial-replay');for(let i=0;i<7;i++)await click('tutorial-next');assert.equal(read().tutorial.status,'completed');assert.deepEqual([api.getState().day,api.getState().minute],initialDate);await click('close');await click('primary');assert.equal($('#modal-body').scrollTop,0);await click('beta-begin');console.log('PASS: compact setup, tutorial start/back/skip/replay/finish without time changes, school acknowledgement scroll retained, new navigation reset.');
const s=api.getState();function at(day=1,minute=520){s.day=day;s.minute=minute;s.room=s.classLocation='classroom';s.journey=null;s.groupActivity=null;s.teacherPlanner.entries=[];api.commit();}
at();api.open('community');hydrate();assert.match($('#modal-title').textContent,/사람과 일상/);await click('beta-belongings');assert.equal($$('.beta-item-grid article').length,8);$('#cx-inspect-consent').checked=true;await click('beta-inspect','[data-scope="desk"]');assert.equal(read().community.checks[0].consent,true);
const item=s.community.belongings[s.students[0].personKey][0];$('#cx-place-'+item.id).value='lost';await click('beta-item-move',`[data-id="${item.id}"]`);$('#cx-lost-owner-'+item.id).value='s0';$('#cx-clue-'+item.id).value='필통의 이름표와 색을 같이 확인';await click('beta-lost-return');assert.equal(read().community.belongings[s.students[0].personKey][0].place,'bag');await click('beta-aid-lend');const aid=s.community.loans[0];await click('beta-aid-return',`[data-id="${aid.id}"]`);assert.equal(read().community.loans[0].returned,true);
await click('beta-family');$('#cx-parent-name').value='이새봄 보호자';await click('beta-family-add');const parent=Object.values(s.community.guardians).find(g=>g.name==='이새봄 보호자');assert.ok(parent);for(const e of $$(`[data-guardian="${parent.key}"]`))e.checked=true;await click('beta-family-permissions',`[data-id="${parent.key}"]`);$('#cx-message-'+parent.key).value=note;await click('beta-family-message',`[data-id="${parent.key}"]`);assert.ok($$('blockquote').some(x=>x.textContent.includes('구분해서')));$('#cx-consent-'+parent.key).value='교내 독서 발표';await click('beta-consent',`[data-id="${parent.key}"][data-agree="no"]`);assert.equal(read().community.consents[0].agree,false);
at(1,900);api.open('family');hydrate();$('#cx-arrival-name').value='유은결';$('#cx-arrival-gender').value='남';await click('beta-transfer-in');const incoming=s.students.at(-1);assert.equal(s.students.length,9);assert.equal($('#cx-student').value,incoming.id);$('#cx-out-school').value='바다빛초등학교';$('#cx-out-note').value=note;await click('beta-transfer-confirm');assert.match($('#modal-title').textContent,/전출 인계 확인/);await click('beta-transfer-out');assert.equal(read().students.length,8);assert.ok(read().community.transfers.some(t=>t.kind==='out'&&t.student.id===incoming.id));
await click('beta-election-full');await click('beta-election-start');await click('beta-election-nominate');await click('beta-election-campaign','[data-id="poster"]');assert.equal($('[data-action="beta-election-campaign"][data-id="poster"]').disabled,true);await click('beta-election-campaign','[data-id="debate"]');await click('beta-election-vote');assert.ok(read().democracy.elections[0].result);assert.match($('#modal-title').textContent,/전교 임원 선거/);
await click('beta-governance');$('#cx-committee-stand').checked=true;await click('beta-committee-election');assert.equal(read().democracy.committee.length,1);$('#cx-vol-day').value='5';await click('beta-volunteer-add');assert.equal(read().democracy.volunteers.length,1);await click('beta-volunteer-replace');assert.equal(read().democracy.volunteers[0].replacement,'학교 지원 인력 요청');
at(2,900);s.students.forEach(st=>st.after='늘봄');api.open('evaluation');hydrate();$('#cx-assess-subject').value='국어';$('#cx-assess-goal').value=note;await click('beta-assessment-run');for(const st of s.students)$('#cx-evidence-'+st.id).value=note;await click('beta-assessment-save');await click('beta-assessment-final');assert.equal(read().schoolReview.assessments[0].status,'final');assert.equal($('[data-action="beta-assessment-save"]').disabled,true);
await click('beta-operations-detail');$('#cx-prep-detail').value=note;await click('beta-preparation');assert.equal(read().schoolReview.preparation.length,1);$('#cx-workshop-text').value=note;await click('beta-book-workshop');assert.equal(read().schoolReview.workshops.length,1);$('#cx-closure-day').value='7';$('#cx-closure-reason').value='학교 시설 점검에 따른 임시 휴업 결정';await click('beta-school-closure');assert.equal(read().academic.calendar.find(d=>d.day===7).school,false);await click('beta-closure-undo');assert.equal(read().academic.calendar.find(d=>d.day===7).school,true);
api.open('library');hydrate();assert.equal($$('.book-scene').length,12);await click('beta-library','[data-id="umbrella"]');assert.equal($$('.book-scene').length,1);await click('beta-operations-detail');assert.match($('#modal-title').textContent,/학교 운영 세부/);
const {validateSave}=await import(pathToFileURL(root+'/model.js').href);assert.equal(validateSave(read()),true);assert.deepEqual(errors,[]);
console.log('PASS: community, consent, inventory, lost property, aids, private guardian replies, transfers, elections, committee, volunteer cover, assessment, work preparation, illustrated books, closure and save DOM flows. WebGL renderer stubbed; no visual claims.');
at(3,520);api.open('belongings');hydrate();$('#cx-aid').value='독서대';await click('beta-aid-lend');const damaged=s.community.loans.at(-1);$('#cx-aid-condition-'+damaged.id).value='점검 필요';await click('beta-aid-return',`[data-id="${damaged.id}"]`);assert.equal([...$('#cx-aid').options].some(o=>o.value==='독서대'),false);$('#cx-aid-note-'+damaged.id).value='받침이 흔들려 사용을 멈추고 종이 자료로 대체';const budgetBeforeRepair=s.budget;await click('beta-aid-repair',`[data-id="${damaged.id}"]`);assert.equal(read().community.loans.at(-1).repair.status,'requested');assert.ok(s.teacherPlanner.entries.some(e=>e.aidLoanId===damaged.id));at(damaged.repair.due,520);api.open('belongings');hydrate();await click('beta-aid-receive',`[data-id="${damaged.id}"]`);assert.equal(read().community.loans.at(-1).repair.status,'closed');assert.ok([...$('#cx-aid').options].some(o=>o.value==='독서대'));$('#cx-aid').value='독서대';await click('beta-aid-lend');assert.equal(s.budget,budgetBeforeRepair);assert.equal(validateSave(read()),true);console.log('PASS: actual DOM damaged return → admin request → scheduled notice → receipt → reloan, without classroom budget charge.');
// Choice-first forms and the actual new staff workflow, using the same DOM handlers as players.
at(10,520);api.staffList();hydrate();assert.equal($$('.staff-task').length,16);await click('staff-chat','[data-id="aftercare"]');
const choose=(id,value)=>{const select=$('#'+id);assert.ok(select);select.value=value;select.dispatchEvent(new win.Event('change',{bubbles:true}));};
assert.equal($('#message-text').hidden,true);assert.equal([...$('#message-text-choices').options].at(-1).value,'other');
choose('message-text-choices','other');assert.equal($('#message-text').hidden,false);$('#message-text').value='오늘 오후 학생의 물통 인계 방법을 알려 주세요.';$('#message-text').dispatchEvent(new win.Event('input',{bubbles:true}));choose('message-text-choices','0');assert.equal($('#message-text').hidden,true);assert.ok($('#message-text').value.includes('확인'));choose('message-text-choices','other');assert.match($('#message-text').value,/물통/);$('#message-form').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setImmediate(r));hydrate();assert.equal(read().staffNetwork.queue.at(-1).status,'waiting');const pendingCount=s.messages.length;api.commit();assert.equal(s.messages.length,pendingCount);
await click('chat-suggestion');const sent=$$('[data-action="chat-suggestion"]').find(b=>b.disabled);assert.ok(sent);assert.equal(sent.getAttribute('aria-disabled'),'true');
s.minute=780;api.commit();api.messenger('staff');hydrate();assert.equal(s.staffNetwork.queue.every(q=>q.status==='answered'),true);assert.ok($$('.message').some(m=>m.textContent.includes('배소연')));
await click('staff-consult');const requestedSlot=$('#staff-slot').value;await click('staff-request');const consultation=s.staffNetwork.consultations.at(-1);assert.equal(consultation.status,'requested');assert.equal($('#toast').parentElement,$('#modal'));assert.ok($('#toast').classList.contains('show'));
s.minute+=2;api.commit();api.staffConsult('aftercare',consultation.id);hydrate();assert.equal(consultation.status,'scheduled');s.day=consultation.day;s.minute=consultation.start-10;api.commit();await click('go-room','[data-id="art"]');api.staffConsult('aftercare',consultation.id);hydrate();choose('staff-note-'+consultation.id+'-choices','0');await click('staff-attend',`[data-id="${consultation.id}"]`);assert.equal(read().staffNetwork.consultations.at(-1).status,'completed');assert.ok(s.notes.teacher.some(n=>n.text.includes('배소연')));
api.open('governance');hydrate();const cover=s.staffNetwork.covers.find(c=>c.status==='reported');assert.ok(cover);await click('beta-cover-ack',`[data-id="${cover.id}"]`);assert.equal(read().staffNetwork.covers.find(c=>c.id===cover.id).status,'confirmed');assert.equal(validateSave(read()),true);
console.log('PASS: choices → Other with draft preservation → queued staff messages and disabled replies → request/reply/scheduler → room visit/attendance → school cover receipt. Toast is in the dialog top layer.');
at(258,1000);s.ended=true;s.academic.phase='closed';api.commit();assert.equal(s.ended,false);await click('close');await click('primary');await click('next-day');assert.equal(s.day,259);at(259,1000);await click('primary');await click('week-summary');assert.match($('#modal-title').textContent,/다음 학년도/);assert.ok($('#bc-grade').getBoundingClientRect);await click('beta-career-propose');await click('beta-career-accept');await click('beta-career-next');assert.equal(s.academic.year,2031);assert.equal(s.academic.phase,'preparation');assert.equal(s.career.archives.length,1);assert.equal(validateSave(read()),true);console.log('PASS: February 27 recovery, February 28 close, assignment acceptance and next-year curriculum through actual DOM buttons.');
globalThis.setInterval=originalInterval;console.error=previousError;await win.happyDOM.abort();process.exit(0);
