import test from 'node:test';import assert from 'node:assert/strict';
import * as M from '../dist/model.js';import * as P from '../dist/planner.js';import * as PE from '../dist/pe-equipment.js';import {SchoolAudio} from '../dist/audio.js';
const reload=s=>{assert.equal(M.validateSave(s),true);const copy=M.migrateSave(JSON.parse(JSON.stringify(s)));assert.ok(copy);return copy;};
test('grade meetings are scheduled in research; old upcoming entries migrate but history stays',()=>{
 const s=M.newGame({region:'city'});P.sync(s);const meeting=s.teacherPlanner.entries.find(e=>e.title==='학년회의');assert.ok(meeting);assert.equal(meeting.room,'research');const invitation=s.messages.find(m=>m.appointmentId===meeting.id);assert.match(invitation.text,/교사연구실/);meeting.room='staff';P.sync(s);assert.equal(meeting.room,'research');meeting.status='완료';meeting.room='staff';P.sync(s);assert.equal(meeting.room,'staff');reload(s);
 const region=Object.keys(M.REGIONS).find(k=>M.REGIONS[k].classes===1),small=M.newGame({region});P.sync(small);assert.equal(small.teacherPlanner.entries.some(e=>e.title==='학년회의'),false);
});
test('meeting agenda, attendance and follow-up form one persisted, once-only flow',()=>{
 let s=M.newGame({region:'city'});P.sync(s);let e=s.teacherPlanner.entries.find(e=>e.title==='학년회의');s.day=e.day;s.minute=890;s.room='staff';assert.ok(P.selectAgenda(s,e.id,'equipment'));assert.equal(P.selectAgenda(s,e.id,'equipment'),false);assert.ok(P.attend(s,e.id,'교구를 번갈아 사용하기로 함.').error);s.room='research';assert.ok(P.respond(s,e.id,'참석').ok);assert.ok(P.attend(s,e.id,'교구를 번갈아 사용하기로 함.').ok);assert.equal(s.minute,920);const task=s.teacherPlanner.entries.find(t=>t.originMeeting===e.id);assert.ok(task);assert.match(task.title,/교구/);assert.ok(P.attend(s,e.id,'중복').error);s=reload(s);assert.equal(s.teacherPlanner.entries.filter(t=>t.originMeeting===e.id).length,1);assert.ok(P.completeFollowup(s,task.id,'').error);const before=s.minute,relation=s.npcRelations.colleague;assert.ok(P.completeFollowup(s,task.id,'체육도구 3종과 모둠별 사용 순서를 정리해 공유함.').ok);assert.equal(s.minute,before+10);assert.equal(s.npcRelations.colleague,relation+1);assert.match(s.notes.teacher[0].text,/공유함/);assert.ok(P.completeFollowup(s,task.id,'중복').error);assert.equal(s.minute,before+10);reload(s);
});
test('shared PE equipment respects location and selection limits, budget and save validation',()=>{
 const s=M.newGame(),budget=s.budget;assert.ok(PE.toggle(s,'ball').error);s.room='gym';assert.ok(PE.toggle(s,'ball').ok);assert.ok(PE.toggle(s,'mats').ok);assert.ok(PE.toggle(s,'cones').ok);assert.ok(PE.toggle(s,'hoops').error);assert.deepEqual(PE.selected(s),['ball','mats','cones']);assert.equal(s.budget,budget);reload(s);assert.ok(PE.toggle(s,'ball').ok);assert.equal(s.equipmentHistory[0].action,'반납');s.room='playground';assert.ok(PE.toggle(s,'mats').error);assert.ok(PE.toggle(s,'beanbags').ok);assert.equal(s.budget,budget);const bad=structuredClone(s);bad.peEquipment.playground=['mats'];assert.equal(M.validateSave(bad),false);const old=structuredClone(s);delete old.peEquipment;delete old.equipmentHistory;assert.deepEqual(reload(old).peEquipment,{gym:[],playground:[]});
});
test('selected equipment is locked in activity, recorded in PE, then returned once',()=>{
 let s=M.newGame({grade:6,count:4});s.day=s.schedule.findIndex(day=>day.some(l=>l.subject==='체육'&&!l.specialist));const slot=s.schedule[s.day].find(l=>l.subject==='체육'&&!l.specialist);s.minute=slot.start;M.takeAttendance(s,{});assert.ok(M.travelTogether(s,'gym','pe'));for(const id of ['ball','cones','hoops'])assert.ok(PE.toggle(s,id).ok);const a=M.beginGroupActivity(s,'pe',{choice:0,method:'m1'});assert.ok(a);assert.deepEqual(a.equipment,['ball','cones','hoops']);assert.ok(PE.toggle(s,'ball').error);const bad=structuredClone(s);bad.groupActivity.equipment='ball';assert.equal(M.validateSave(bad),false);s=reload(s);s.groupActivity.elapsed=s.groupActivity.duration;assert.ok(M.completeGroupActivity(s,a.id));assert.deepEqual(s.lessonResults.at(-1).equipment,['ball','cones','hoops']);assert.deepEqual(PE.selected(s),[]);assert.equal(s.equipmentHistory.filter(e=>e.action==='반납').length,1);assert.equal(M.completeGroupActivity(s,a.id),false);reload(s);
});
test('audio only starts after unlock, honors mute/volume and visibility, and throttles footsteps',()=>{
 const calls=[],gainValues=[],a={state:'suspended',currentTime:0,destination:{},resume(){this.state='running';calls.push('resume');return Promise.resolve();},createGain(){return {gain:{cancelScheduledValues(){},setValueAtTime(v){gainValues.push(v);},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};},createOscillator(){return {frequency:{setValueAtTime(n){calls.push(n);}},connect(){},disconnect(){},start(){calls.push('start');},stop(){}};}};let contexts=0;const sound=new SchoolAudio(()=>{contexts++;return a;});sound.configure({sound:true,volume:30});assert.equal(sound.play('bell'),false);assert.equal(contexts,0);assert.ok(sound.unlock());assert.equal(contexts,1);assert.equal(gainValues[0],.3);sound.play('message');const n=calls.filter(x=>x==='start').length;assert.equal(n,2);sound.configure({sound:false,volume:30});assert.equal(sound.play('bell'),false);assert.equal(gainValues.at(-1),0);sound.configure({sound:true,volume:50});sound.visibility(true);assert.equal(sound.note(0),false);assert.equal(gainValues.at(-1),0);sound.visibility(false);assert.ok(sound.play('step'));assert.equal(sound.play('step'),false);a.currentTime=.4;assert.ok(sound.play('step'));assert.ok(sound.note(3,'piano'));assert.equal(sound.note(9,'piano'),false);sound.unlock();assert.equal(contexts,1);
});
