// Executes the actual scene movement and mesh geometry without a browser or WebGL renderer.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as THREE from '../dist/assets/three.module.js';import * as M from '../dist/model.js';
const source=fs.readFileSync(new URL('../dist/scene.js',import.meta.url),'utf8').replace("from './staff-catalog.js'",`from '${new URL('../dist/staff-catalog.js',import.meta.url)}'`).replace("from './staff-network.js'",`from '${new URL('../dist/staff-network.js',import.meta.url)}'`).replace("from './character-rig.js'",`from '${new URL('../dist/character-rig.js',import.meta.url)}'`).replace("from './student-support.js'",`from '${new URL('../dist/student-support.js',import.meta.url)}'`).replace("from 'three'",`from '${new URL('../dist/assets/three.module.js',import.meta.url)}'`).replace("from './model.js'",`from '${new URL('../dist/model.js',import.meta.url)}'`).replace("from './portraits.js'",`from '${new URL('../dist/portraits.js',import.meta.url)}'`).replace("from './world.js'",`from '${new URL('../dist/world.js',import.meta.url)}'`).replace("from './themes.js'",`from '${new URL('../dist/themes.js',import.meta.url)}'`).replace("from './pe-equipment.js'",`from '${new URL('../dist/pe-equipment.js',import.meta.url)}'`);
const {ClassroomScene}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
function geometryScene(state){const scene=Object.create(ClassroomScene.prototype);Object.assign(scene,{getState:()=>state,world:new THREE.Group(),camera:new THREE.OrthographicCamera(),renderer:{setSize(){}},canvas:{parentElement:{clientWidth:1024,clientHeight:768},clientHeight:768},actors:new Map(),materials:new Map(),targets:[],blockers:[],path:[],keys:{},joy:{x:0,y:0},bubbles:[],pan:{x:0,z:0},angle:0,zoom:1,mural:new THREE.Texture()});scene.textPlane=(text,w,h)=>{const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial());const context={fillRect(){},fillText(){}};mesh.userData.canvasTexture={dispose(){},image:{width:1024,height:512,getContext:()=>context}};return mesh;};scene.onJourneyStage=({id,stage,arrivedIds})=>{assert.equal(arrivedIds.length,state.journey.memberIds.length);assert.ok(M.completeJourneyStage(state,id,stage,arrivedIds));scene.sync();};scene.sync(true);return scene;}
function walk(scene,state){const firstPositions=new Map([...scene.actors].filter(([id])=>/^s\d+$/.test(id)).map(([id,a])=>[id,a.group.position.clone()]));let moved=false,ticks=0;while(state.journey.status==='moving'&&ticks++<10000){scene.updateJourney(.05);if(ticks===20)moved=[...firstPositions].some(([id,p])=>p.distanceTo(scene.actors.get(id).group.position)>.1);}const r=scene.journeyRuntime;assert.equal(state.journey.status,'arrived',JSON.stringify({room:state.room,layout:state.layout,count:state.students.length,stage:state.journey.stage,phase:r?.phase,arrived:r?.arrived.size,teacher:scene.teacher.group.position,path:scene.path.length,missing:r?.members.filter((a,i)=>r.phase==='gathering'?Math.hypot(a.group.position.x-r.points.queue[i].x,a.group.position.z-r.points.queue[i].z)>.18:!r.arrived.has(a.data.id)).map(a=>({id:a.data.id,x:a.group.position.x,z:a.group.position.z,home:a.home,route:r.paths.get(a.data.id)?.length}))}));assert.ok(moved,'students must visibly leave their initial position');}
for(const count of [4,28])for(const layout of ['rows','groups','u'])test(`${count} students in ${layout}: queue, corridor, cafeteria, lunch, and classroom return`,()=>{const state=M.newGame({count});state.layout=layout;state.minute=730;M.beginJourney(state,'cafeteria','lunch');const scene=geometryScene(state);walk(scene,state);assert.ok(M.canStartGroupActivity(state,'lunch'));M.beginGroupActivity(state,'lunch');scene.onActivityComplete=id=>M.completeGroupActivity(state,id);for(let i=0;i<130;i++)scene.updateGroupActivity(.05,i*50);assert.ok(M.done(state,'lunch'));assert.equal(state.room,'cafeteria');M.beginJourney(state,'classroom','return');scene.sync();walk(scene,state);assert.equal(state.minute,790);});
test('playground has the entire class, moves with teacher, and plays on site',()=>{const state=M.newGame({count:28});M.beginJourney(state,'playground','play');const scene=geometryScene(state);walk(scene,state);assert.equal([...scene.actors].filter(([id])=>/^s\d+$/.test(id)).length,28);M.beginGroupActivity(state,'play');scene.onActivityComplete=id=>M.completeGroupActivity(state,id);for(let i=0;i<165;i++)scene.updateGroupActivity(.05,i*50);assert.equal(state.journey.activityDone,true);M.beginJourney(state,'classroom','return');scene.sync();walk(scene,state);assert.equal(state.minute,530);});
test('zoom clamps, reset and pan retain a valid orthographic view',()=>{const state=M.newGame();const scene=geometryScene(state);scene.setZoom(2.4);assert.equal(scene.zoom,2);scene.panBy(120,60);assert.notEqual(scene.pan.x,0);scene.resetView();assert.equal(scene.zoom,1);assert.equal(scene.angle,0);assert.deepEqual(scene.pan,{x:0,z:0});scene.setZoom(.2);assert.equal(scene.zoom,.5);assert.ok(scene.camera.top>scene.camera.bottom);});
test('all school and community rooms build with accessible floors, and the L-shaped library has a true cutout',()=>{const types=new Set();for(const room of Object.keys(M.ROOMS)){const state=M.newGame({count:4});state.room=room;const scene=geometryScene(state);assert.ok(scene.floor.userData.floor);assert.ok(scene.camera.top>0);assert.ok(scene.actors.has('teacher'));types.add(scene.world.children.length);if(room==='library'){scene.world.updateMatrixWorld(true);const ray=new THREE.Raycaster(new THREE.Vector3(-7,10,5),new THREE.Vector3(0,-1,0));assert.equal(ray.intersectObject(scene.floor).length,0);ray.set(new THREE.Vector3(0,10,5),new THREE.Vector3(0,-1,0));assert.ok(ray.intersectObject(scene.floor).length>0);}}assert.ok(types.size>=11,'spaces must not reuse a single furnishing layout');});
test('teacher controls and NPC walking translate in eight discrete directions',()=>{const state=M.newGame();state.room='hall';const scene=geometryScene(state);for(const [dx,dz] of [[0,-1],[1,-1],[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1]]){scene.teacher.group.position.set(0,0,5);scene.joy={x:dx,y:dz};scene.driveTeacher(.1);const p=scene.teacher.group.position;assert.ok(Math.abs(Math.hypot(p.x,p.z-5)-.36)<1e-8);assert.ok(Math.abs(scene.teacher.group.rotation.y/(Math.PI/4)-Math.round(scene.teacher.group.rotation.y/(Math.PI/4)))<1e-8);}const a=scene.actors.get('neulbom');a.group.position.set(0,0,0);scene.moveActorToward(a,{x:3,z:1},.1,1);assert.ok(Math.abs(a.group.position.z)<1e-8);assert.ok(Math.abs(a.group.position.x-.1)<1e-8);});
test('28 students complete a gym PE lesson and return after the eight-direction conversion',()=>{const state=M.newGame({grade:6,count:28});state.day=state.schedule.findIndex(d=>d.some(l=>l.subject==='체육'&&!l.specialist));const lesson=state.schedule[state.day].find(l=>l.subject==='체육'&&!l.specialist);state.minute=lesson.start;M.beginJourney(state,'gym','pe');const scene=geometryScene(state);walk(scene,state);assert.ok(M.beginGroupActivity(state,'pe',{choice:0,mode:'모둠 수업'}));scene.onActivityComplete=id=>M.completeGroupActivity(state,id);for(let i=0;i<165;i++)scene.updateGroupActivity(.05,i*50);assert.equal(state.progress['체육'],1);M.beginJourney(state,'classroom','return');scene.sync();walk(scene,state);assert.equal(state.minute,lesson.end);});

test('all seat layouts keep every seated student clear of chair backs at grades 1 and 6',()=>{
 for(const grade of [1,6])for(const layout of ['rows','groups','u']){
  const state=M.newGame({grade,count:28});state.layout=layout;state.minute=540;const scene=geometryScene(state);scene.world.updateMatrixWorld(true);const backs=[];scene.world.traverse(o=>{if(o.userData.backrest)backs.push(new THREE.Box3().setFromObject(o));});assert.equal(backs.length,28);
  for(const [id,a] of scene.actors){if(!/^s\d+$/.test(id))continue;assert.equal(a.seated,true);const box=new THREE.Box3().setFromObject(a.group);for(const back of backs)assert.equal(box.intersectsBox(back),false,`${grade}/${layout}/${id} clips a chair back`);assert.equal(a.walking,false);}
  state.minute=580;scene.updateSeating();for(const [id,a] of scene.actors)if(/^s\d+$/.test(id))assert.equal(a.seated,false);
 }
});
test('zoomed name labels honor settings, visibility and gesture cancellation',()=>{
 const state=M.newGame({count:4}),scene=geometryScene(state),prior=globalThis.document;const layer={hidden:true,appendChild(el){this.children.push(el);},children:[]};
 globalThis.document={getElementById:id=>id==='name-layer'?layer:null,querySelector:()=>null,createElement:()=>({style:{},hidden:false})};
 try{scene.canvas.clientWidth=1024;scene.zoom=1.24;scene.updateNameLabels();assert.equal(layer.hidden,true);scene.zoom=1.25;scene.updateNameLabels();assert.equal(layer.children.length,4);assert.equal(layer.children[0].textContent,state.students[0].name);assert.equal(layer.hidden,false);scene.actors.get('s0').group.visible=false;scene.updateNameLabels();assert.equal(layer.children[0].hidden,true);scene.getNameLabels=()=>false;scene.updateNameLabels();assert.equal(layer.hidden,true);
  const events={};scene.canvas.addEventListener=(type,fn)=>events[type]=fn;scene.canvas.setPointerCapture=()=>{};scene.pointers=new Map();let clicked=0;scene.click=()=>clicked++;scene.installPointerControls();const e=(x,y)=>({pointerId:1,clientX:x,clientY:y,button:0,preventDefault(){}});
  events.pointerdown(e(100,100));events.pointermove(e(140,100));events.pointermove(e(100,100));events.pointerup({...e(100,100),type:'pointerup'});assert.equal(clicked,0,'dragging away and back must not activate a student');events.pointerdown(e(100,100));events.pointerup({...e(100,100),type:'pointerup'});assert.equal(clicked,1,'intentional taps still work');
 }finally{if(prior===undefined)delete globalThis.document;else globalThis.document=prior;}
});

test('break-time pupils roam away from desks on clear paths and return for the next lesson',()=>{
 for(const layout of ['rows','groups','u']){
  const state=M.newGame({count:28});state.layout=layout;state.minute=580;const scene=geometryScene(state);const maximum=new Map();
  for(let frame=0;frame<700;frame++){scene.updateStudents(.05,frame*50);for(const [id,a] of scene.actors){if(!/^s\d+$/.test(id))continue;maximum.set(id,Math.max(maximum.get(id)||0,a.group.position.distanceTo(a.home)));assert.equal(scene.blocked(a.group.position.x,a.group.position.z,0),false,layout+' '+id+' moved through furniture');}}
  assert.ok([...maximum.values()].filter(d=>d>2).length>=20,layout+': most students must leave their own desks');
  state.minute=590;scene.sync();for(let frame=0;frame<600;frame++){scene.updateStudents(.05,40000+frame*50);scene.updateSeating();}for(const [id,a] of scene.actors)if(/^s\d+$/.test(id)){assert.ok(a.group.position.distanceTo(a.home)<.09,layout+' '+id+' did not return');assert.equal(a.seated,true);}
 }
});

test('classrooms retain a moderate teaching area in front of the first desks and size furniture to pupils',()=>{
 for(const grade of [1,6])for(const count of [4,20,28])for(const layout of ['rows','groups','u']){
  const state=M.newGame({grade,count});state.layout=layout;state.minute=540;const scene=geometryScene(state);scene.world.updateMatrixWorld(true);
  const desks=scene.world.children.filter(o=>o.userData.studentDesk),tops=desks.map(g=>{let top;g.traverse(o=>{if(o.userData.desktop)top=o;});return new THREE.Box3().setFromObject(top);});assert.equal(desks.length,count);
  const gap=Math.min(...tops.map(b=>b.min.z))-scene.board.position.z;assert.ok(gap>2.85&&gap<3.4,`${grade}/${count}/${layout} front gap ${gap}`);
  for(const [id,a] of scene.actors)if(/^s\d+$/.test(id)){scene.setSeated(a,false);scene.world.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(a.group),top=tops[0],height=box.max.y-box.min.y;assert.ok(top.max.y/height>.65&&top.max.y/height<.8,'desktop should be comfortably below a standing pupil head');assert.ok(top.max.x-top.min.x<1.12,'desk width is compact, including rotated desks');assert.equal(scene.blocked(a.home.x,a.home.z,0),false);}
 }
});

test('music chairs and music stands face the front, away from their backrests',()=>{const s=M.newGame();s.room='music';const scene=geometryScene(s),chairs=scene.world.children.filter(o=>o.userData.musicChair),stands=scene.world.children.filter(o=>o.userData.musicStand);assert.equal(chairs.length,10);assert.equal(stands.length,10);chairs.forEach((chair,i)=>{const forward=new THREE.Vector3(0,0,-1).applyAxisAngle(new THREE.Vector3(0,1,0),chair.rotation.y),toFront=new THREE.Vector3(-chair.position.x,0,-5.6-chair.position.z).normalize(),toStand=stands[i].position.clone().sub(chair.position);toStand.y=0;assert.ok(forward.dot(toFront)>.999);assert.ok(forward.dot(toStand.normalize())>.999);});assert.ok(scene.targets.some(o=>o.userData.object==='instrument'));});
test('research room is furnished for teachers and has a reachable schedule interaction',()=>{const s=M.newGame();s.room='research';const scene=geometryScene(s);assert.equal([...scene.actors.keys()].filter(id=>/^s\d+$/.test(id)).length,0);assert.ok(scene.actors.has('colleague'));assert.ok(scene.actors.has('specialist'));assert.ok(scene.targets.some(o=>o.userData.object==='planner'));assert.equal(scene.blocked(scene.teacher.home.x,scene.teacher.home.z),false);});
test('themes change real classroom materials and selected PE tools change venue geometry',()=>{const floors=new Set(),walls=new Set();for(const theme of ['mint','sky','yellow','navy']){const s=M.newGame();s.theme=theme;const scene=geometryScene(s);floors.add(scene.floor.material.color.getHex());walls.add(scene.world.children.find(o=>o.geometry?.parameters?.height===3.5).material.color.getHex());}assert.equal(floors.size,4);assert.equal(walls.size,4);for(const room of ['gym','playground']){const s=M.newGame();s.room=room;s.peEquipment[room]=['cones','hoops','beanbags'];const scene=geometryScene(s);assert.deepEqual(scene.world.children.filter(o=>o.userData.equipmentId).map(o=>o.userData.equipmentId),s.peEquipment[room]);assert.ok(scene.targets.some(o=>o.userData.object==='pe-equipment'));s.peEquipment[room]=['ball'];scene.sync();assert.equal(scene.world.children.filter(o=>o.userData.equipmentId).length,1);assert.ok(scene.ball);}});


test('Theta free roaming changes routes with independent random seeds and uses all eight headings',()=>{
 const run=seed=>{const state=M.newGame({count:28});state.minute=580;const scene=geometryScene(state);scene.wanderRandom=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const headings=new Set(),destinations=new Map(),departures=new Map();for(let frame=0;frame<500;frame++){scene.updateStudents(.05,frame*50);for(const [id,a] of scene.actors)if(/^s\d+$/.test(id)){if(a.walking){headings.add((Math.round(a.group.rotation.y/(Math.PI/4))+8)%8);if(!departures.has(id))departures.set(id,frame);}if(a.freeGoal&&!destinations.has(id))destinations.set(id,[a.freeGoal.x,a.freeGoal.z]);}}assert.equal(headings.size,8);assert.ok(new Set(departures.values()).size>8);assert.equal(destinations.size,28);return destinations;};
 const a=run(43),b=run(109);assert.ok([...a].filter(([id,point])=>JSON.stringify(point)!==JSON.stringify(b.get(id))).length>=24,'student ID must not impose a fixed destination');
});
test('Theta physical teacher computer opens its desktop and clock hands follow game time',()=>{
 const state=M.newGame({count:4}),scene=geometryScene(state),clickable=[];scene.world.traverse(o=>{if(o.userData.object==='computer')clickable.push(o);});assert.ok(clickable.length>10);assert.ok(scene.wallClock);state.minute=575;scene.sync();assert.ok(Math.abs(scene.wallClock.minute.rotation.z-(-35/60*Math.PI*2))<1e-8);assert.ok(Math.abs(scene.wallClock.hour.rotation.z-(-575/720*Math.PI*2))<1e-8);
});

test('Iota wood materials, rounded furniture, room shadows and field nets retain valid geometry and release nets on room changes',()=>{
 const state=M.newGame({count:4}),scene=geometryScene(state);scene.woodTexture=new THREE.Texture();scene.sun=new THREE.DirectionalLight();scene.sync(true);
 const woods=[],rounded=[];scene.world.traverse(o=>{if(o.userData.woodSurface)woods.push(o);if(o.userData.rounded)rounded.push(o);});assert.ok(woods.length>=6);assert.ok(rounded.length>=20);assert.ok(woods.every(o=>o.material.map===scene.woodTexture&&o.material.bumpMap===scene.woodTexture));
 for(const mesh of rounded){const p=mesh.geometry.attributes.position,n=mesh.geometry.attributes.normal;assert.ok([...p.array,...n.array].every(Number.isFinite));mesh.geometry.computeBoundingBox();const size=mesh.geometry.boundingBox.getSize(new THREE.Vector3()),params=mesh.geometry.parameters;assert.ok(Math.abs(size.x-params.width)<1e-5);assert.ok(Math.abs(size.y-params.height)<1e-5);assert.ok(Math.abs(size.z-params.depth)<1e-5);}
 const indoorRange=scene.sun.shadow.camera.right;state.room='playground';scene.sync();assert.ok(scene.sun.shadow.camera.right>indoorRange);const nets=[];scene.world.traverse(o=>{if(o.isLineSegments)nets.push(o);});assert.equal(nets.length,2);let geometryDisposed=0,materialsDisposed=0;for(const n of nets){n.geometry.addEventListener('dispose',()=>geometryDisposed++);n.material.addEventListener('dispose',()=>materialsDisposed++);}state.room='classroom';scene.sync();assert.equal(geometryDisposed,2);assert.equal(materialsDisposed,2);
});

test('Iota pupils use 15 percent slower free movement while retaining independent speeds',()=>{
 const state=M.newGame({count:28});state.minute=580;const scene=geometryScene(state);let seed=123;scene.wanderRandom=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let frame=0;frame<50;frame++)scene.updateStudents(.05,frame*50);const speeds=[...scene.actors].filter(([id])=>/^s\d+$/.test(id)).map(([,a])=>a.walkSpeed);assert.ok(speeds.every(speed=>speed>=.8*.85&&speed<=1.3*.85));assert.ok(new Set(speeds).size>20);
});

test('support NPCs occupy reachable locations in their own rooms and appear only during duty',()=>{
 for(const id of ['nutrition','inclusion','facilities','aftercare','registrar','ict']){const n=M.NPCS.find(n=>n.id===id),s=M.newGame({count:4});s.room=n.room;s.minute=900;const scene=geometryScene(s),actor=scene.actors.get(id);assert.ok(actor,id+' should be present');assert.equal(scene.blocked(actor.home.x,actor.home.z,.3),false,id+' should not overlap furniture');assert.ok(scene.targets.some(o=>o.userData.character===id));assert.equal([...scene.actors.keys()].filter(k=>k===id).length,1);}
 const s=M.newGame();s.room='art';s.minute=779;const scene=geometryScene(s);assert.equal(scene.actors.has('aftercare'),false);s.minute=780;scene.sync();assert.equal(scene.actors.has('aftercare'),true);s.minute=1000;scene.sync();assert.equal(scene.actors.has('aftercare'),false);
});
test('daylight color changes with game time and soft contact shadows do not become click targets',()=>{
 const s=M.newGame({count:4}),scene=geometryScene(s);scene.sun=new THREE.DirectionalLight();scene.ambient=new THREE.HemisphereLight();scene.updateLighting();const morning=scene.sun.color.getHex();s.minute=990;scene.updateLighting();assert.notEqual(scene.sun.color.getHex(),morning);assert.ok(scene.world.children.some(g=>g.userData.windowLight));let shadows=0;scene.world.traverse(o=>{if(o.userData.contactShadow){shadows++;assert.equal(scene.targets.includes(o),false);assert.equal(o.material.depthWrite,false);assert.ok(o.material.opacity<=.3);}});assert.equal(shadows,5);assert.ok(scene.materials.get('character-contact-shadow').map.isDataTexture);assert.ok(scene.sun.intensity>=1.9);
});
