import test from 'node:test';import assert from 'node:assert/strict';
import * as M from '../dist/model.js';import * as S from '../dist/sports-day.js';import * as P from '../dist/planner.js';
const reload=s=>{const r=M.migrateSave(JSON.parse(JSON.stringify(s)));assert.ok(r,'save must remain loadable');return r;};
function ready(s,day=2){assert.ok(S.create(s,day,['rolling','beanbag','relay']).ok);for(const event of s.sportsDay.events){const willing=s.students.filter(st=>S.willing(s,event.id,st.id));assert.ok(S.assign(s,event.id,[willing[0].id],willing[1]?.id).ok);assert.ok(S.practice(s,event.id).ok);}assert.ok(S.confirm(s).ok);return s;}
test('sports planning links one annual event, practice, parent notices and an approved timetable',()=>{
 const s=M.newGame({count:4}),base=structuredClone(s.schedule),budget=s.budget;ready(s);P.sync(s);assert.equal(s.teacherPlanner.entries.filter(e=>e.type==='event').length,1);assert.equal(s.schoolLife.notices[0].recipients.length,4);assert.equal(s.schoolLife.notices[0].requiresReply,false);assert.equal(s.budget,budget);assert.deepEqual(s.schedule,base);assert.ok(M.todaySchedule({...s,day:2}).slice(0,4).every(x=>x.event==='sportsday'&&!x.specialist));assert.deepEqual(M.todaySchedule({...s,day:1}),base[1]);assert.ok(S.confirm(s).error);assert.ok(S.create(s,4,['rolling','beanbag','relay']).error);reload(s);
});
test('sports day substitutes an absent representative, records every present role, and completes once',()=>{
 let s=ready(M.newGame({count:4,grade:6}));const absent=s.sportsDay.events[0].main[0],reserve=s.sportsDay.events[0].reserve,before=structuredClone(s.students.map(st=>st.scores));s.day=2;s.minute=540;M.takeAttendance(s,{[absent]:'질병결석'});assert.ok(S.start(s).ok);assert.equal(s.minute,544);assert.equal(s.room,'playground');const part=S.participation(s,0);assert.ok(part.main.includes(reserve));assert.ok(part.replaced.includes(absent));assert.equal(part.roles.length,3);assert.ok(S.step(s,0,0).ok);assert.ok(S.step(s,0,0).error,'a duplicate click must not complete the next round');s=reload(s);for(let i=1;i<4;i++)assert.ok(S.step(s,1,i).ok);assert.equal(s.sportsDay.stage,'completed');assert.equal(s.room,'classroom');assert.equal(s.minute,730);assert.equal(M.currentSlot(s).kind,'lunch');assert.ok(S.step(s,0).error);assert.equal(s.students.find(st=>st.id===absent).memories.length,0);assert.deepEqual(s.students.map(st=>st.scores),before);assert.deepEqual(s.progress,{});assert.equal(P.data(s).entries.find(e=>e.id===s.sportsDay.id).status,'완료');reload(s);
});
test('weather changes preserve the event ID, update notices and allow the indoor alternative',()=>{
 const s=ready(M.newGame({count:4}),3),id=s.sportsDay.id;s.day=3;s.minute=520;const notices=s.schoolLife.notices.length;assert.ok(S.change(s,3,'gym','우천으로 실내 활동 협의').ok);assert.equal(s.sportsDay.id,id);assert.equal(s.sportsDay.changes.length,1);assert.equal(s.schoolLife.notices.length,notices+1);assert.equal(P.data(s).entries.filter(e=>e.id===id).length,1);assert.equal(P.data(s).entries.find(e=>e.id===id).room,'gym');s.minute=540;M.takeAttendance(s,{});assert.ok(S.start(s).ok);assert.equal(s.room,'gym');reload(s);
 const rain=ready(M.newGame({count:4}),3);rain.day=3;rain.minute=540;M.takeAttendance(rain,{});assert.ok(S.start(rain).error);assert.equal(rain.room,'classroom');
});
test('participation requests, school time and cancellation keep records honest',()=>{
 const s=M.newGame({count:28});assert.ok(S.create(s,4,['rolling','beanbag','relay']).ok);const no=s.students.find(st=>!S.willing(s,'rolling',st.id));assert.ok(S.assign(s,'rolling',[no.id],null).error);const st=s.students.find(st=>S.willing(s,'rolling',st.id));assert.ok(S.assign(s,'rolling',[st.id],st.id).error);s.minute=540;assert.ok(S.practice(s,'rolling').error);s.minute=539;assert.ok(S.practice(s,'rolling').error);s.minute=520;assert.ok(S.cancel(s,'학교와 우천 일정 협의 후 취소').ok);assert.equal(P.data(s).entries.find(e=>e.id===s.sportsDay.id).status,'취소');assert.ok(M.todaySchedule({...s,day:4}).every(x=>!x.event));assert.ok(S.start(s).error);reload(s);
 const empty=ready(M.newGame({count:4}));empty.day=2;empty.minute=540;M.takeAttendance(empty,Object.fromEntries(empty.students.map(st=>[st.id,'질병결석'])));assert.ok(S.start(empty).error);assert.equal(empty.sportsDay.rounds.length,0);
});
test('older saves migrate and malformed sports state is rejected',()=>{
 const old=M.newGame();delete old.sportsDay;assert.equal(reload(old).sportsDay,null);const s=ready(M.newGame({count:4}));const bad=structuredClone(s);bad.sportsDay.events[0].main=['missing'];assert.equal(M.validateSave(bad),false);const done=structuredClone(s);done.sportsDay.stage='completed';assert.equal(M.validateSave(done),false);const other=structuredClone(s);other.students.forEach(st=>{st.gender='여';st.tag='다른 배경';st.relation=100;st.scores['체육']=100;});assert.deepEqual(s.students.map(st=>S.willing(s,'rolling',st.id)),other.students.map(st=>S.willing(other,'rolling',st.id)));
});
