import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const file=path.join(root,'docs/releases.json'),history=JSON.parse(fs.readFileSync(file,'utf8'));
const args=process.argv.slice(2);let version,label,changes;
const next=()=>{const current=history[0]?.version||'0.0.0',match=/^(\d+)\.(\d+)\.(\d+)-beta\.(\d+)$/.exec(current);return match?`${match[1]}.${match[2]}.${match[3]}-beta.${Number(match[4])+1}`:'1.0.0-beta.1';};
if(args[0]==='--next'||args[0]==='--auto'){version=next();label='정식 베타';changes=args.slice(1);if(args[0]==='--auto'){const changed=execFileSync('git',['diff','--cached','--name-only'],{cwd:root,encoding:'utf8'}).trim().split('\n');const themes=[[/academic|class-curriculum|curriculum-ui/,'학교·학급교육과정과 학사 일정 개선'],[/career/,'학년 배정·전근·인연 기록 개선'],[/support|school-life|dialogue/,'학생 지원과 대화 흐름 개선'],[/scene|world|css/,'학교 공간·그래픽·화면 배치 개선'],[/staff|teacher-pc|planner/,'교사 업무·일정·학교톡 개선'],[/library|record|suppl/,'독서·기록·물품 관리 개선']];changes=themes.filter(([re])=>changed.some(f=>re.test(f))).map(([,t])=>t);if(!changes.length)changes=['게임 화면과 기능을 수정하고 동작을 확인했습니다.'];changes=changes.slice(0,4);}}
else [version,label,...changes]=args;
if(!/^\d+\.\d+\.\d+(?:-[a-z]+(?:\.\d+)?)?$/.test(version||'')||!label||!changes.length)throw Error('Usage: node scripts/release.mjs --next CHANGE [CHANGE...] | VERSION LABEL CHANGE [CHANGE...]');
if(history.some(r=>r.version===version))throw Error('A published version number must not be reused: '+version);
const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const entry={version,label,date,changes},releases=[entry,...history];
fs.writeFileSync(file,JSON.stringify(releases,null,2)+'\n');
fs.writeFileSync(path.join(root,'dist/release-info.js'),'// Generated by scripts/release.mjs; newest three records are displayed in-game.\nexport const RELEASE='+JSON.stringify(entry)+';\nexport const RECENT_RELEASES='+JSON.stringify(releases.slice(0,3))+';\n');
console.log(version+' · '+date+' · recent history generated');
